Manually doing TF-IDF: https://towardsdatascience.com/natural-language-processing-feature-engineering-using-tf-idf-e8b9d00e7e76

In [3]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

%matplotlib inline
# 시각화 결과가 선명하게 표시되도록
%config InlineBackend.figure_format = 'retina'

In [4]:
df = pd.read_csv("combined_wrangling_db.csv")
df.shape

(100, 248)

In [5]:
df.head()

,PTfreq,PT관련명사,PTfreq.1,PT관련서술어,PTfreq.2,PT관련명사.1,PTfreq.3,PT관련서술어.1,검도freq,검도관련명사,...,핫요가freq.1,핫요가관련서술어,헬스freq,헬스관련명사,헬스freq.1,헬스관련서술어,힙레freq,힙레관련명사,힙레freq.1,힙레관련서술어
0,263,운동,13,많은,263,운동,13,많은,2051,검도,...,238,좋아요,1306,운동,110,좋아요,747,힙,76,열리는
1,164,헬스,13,좋아요,164,헬스,13,좋아요,596,운동,...,202,아쉬,953,헬스,107,챌,710,발레,46,자세한
2,102,다이어트,12,들,102,다이어트,12,들,522,검,...,73,다양한,336,다이어트,54,좋은,478,운동,42,이어
3,83,필라테스,9,해서,83,필라테스,9,해서,451,도관,...,69,소소한,270,팔,53,좋,464,포레스티,40,바꿀
4,64,니스,9,좋은,64,니스,9,좋은,232,동검,...,58,들,263,필라테스,47,하면,452,벌,38,되는

In [6]:
df['PT관련명사']

0       운동
1       헬스
2     다이어트
3     필라테스
4       니스
      ...
95     퍼스널
96     코로나
97      교정
98     휘트니
99       손
Name: PT관련명사, Length: 100, dtype: object

In [7]:
bagOfWordsA = df['키네시스관련명사'].to_list()
bagOfWordsA

['키네시스',
 '필라테스',
 '운동',
 '자이로',
 '메이플',
 '사료',
 '토닉',
 '팀',
 '닥터',
 '샵',
 '스토리',
 '대구',
 '피티',
 '교육',
 '반려',
 '일상',
 '근육',
 '몸',
 '니스',
 '웰',
 '아치',
 '수성구',
 '퍼스널',
 '청담',
 '메스타',
 '헬스',
 '여자',
 '국제',
 '견',
 '트레이너',
 '센터',
 '건강',
 '장신구',
 '다이어트',
 '게임',
 '것',
 '시간',
 '팔',
 '데이',
 '강아지',
 '펄',
 '슛',
 '장식',
 '그림',
 '강사',
 '피엠',
 '글로벌',
 '부산',
 '중',
 '육학',
 '애견',
 '오늘',
 '아트',
 '오후',
 '트레이닝',
 '그룹',
 '수업',
 '공근',
 '혜',
 '갤러리',
 '키',
 '감사',
 '번',
 '바디',
 '근',
 '압구정',
 '코스',
 '기능',
 '내',
 '오전',
 '노',
 '클래스',
 '공예',
 '마드',
 '육아',
 '맘',
 '라인',
 '펫',
 '등',
 '전',
 '워커힐',
 '진행',
 '거',
 '한남동',
 '견사',
 '료',
 '아침',
 '소통',
 '요가',
 '나',
 '시작',
 '사진',
 '체형',
 '미',
 '모집',
 '때',
 '팔로우',
 '롬',
 '어깨',
 '날']

In [8]:
bagOfWordsB = df['바차타관련명사'].to_list()
bagOfWordsB

['살사',
 '바차타',
 '댄스',
 '라틴',
 '동호회',
 '홍대',
 '취미',
 '여행',
 '수업',
 '강습',
 '강남',
 '춤',
 '소셜',
 '운동',
 '클럽',
 '다이어트',
 '파티',
 '에버',
 '영어',
 '텐션',
 '활동',
 '공연',
 '파타야',
 '쌤',
 '키',
 '좀바',
 '방콕',
 '모임',
 '커플',
 '나',
 '오사카',
 '바',
 '부산',
 '정모',
 '수원',
 '클래스',
 '일상',
 '쿠바',
 '직장',
 '생활',
 '일본',
 '사진',
 '슈얼',
 '팔',
 '반',
 '초급',
 '스다',
 '연말',
 '시간',
 '맛집',
 '베이직',
 '중',
 '핫',
 '주차',
 '크루',
 '신청',
 '아카데미',
 '연습',
 '소통',
 '맘보',
 '것',
 '홍',
 '번',
 '주',
 '차',
 '설',
 '시작',
 '콜',
 '미군',
 '부대',
 '오픈',
 '음악',
 '새해',
 '여기',
 '달',
 '한곡',
 '완성',
 '거',
 '사랑',
 '블랙',
 '센',
 '콩',
 '속',
 '이번',
 '앵',
 '스터디',
 '언어',
 '교환',
 '특강',
 '서울',
 '벨',
 '영상',
 '친구',
 '전설',
 '수강',
 '토요일',
 '사람',
 '우리',
 '남미',
 '생일']

In [9]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

In [10]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

In [11]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [12]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)

In [13]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [14]:
idfs = computeIDF([numOfWordsA, numOfWordsB])

In [15]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [16]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df_result = pd.DataFrame([tfidfA, tfidfB])

In [17]:
df_result

,혜,마드,음악,애견,메이플,전설,모임,사료,바디,언어,...,육학,갤러리,공연,요가,육아,활동,아카데미,클래스,워커힐,댄스
0,0.006931,0.006931,0.000000,0.006931,0.006931,0.000000,0.000000,0.006931,0.006931,0.000000,...,0.006931,0.006931,0.000000,0.006931,0.006931,0.000000,0.000000,0.0,0.006931,0.000000
1,0.000000,0.000000,0.006931,0.000000,0.000000,0.006931,0.006931,0.000000,0.000000,0.006931,...,0.000000,0.000000,0.006931,0.000000,0.000000,0.006931,0.006931,0.0,0.000000,0.006931

In [19]:
# 0이 키네시스, 1가 차바타
# 높은 순으로 정렬을 했다는 것은 바차타에는 없고(=0), 키네시스에는 있다는 것(=0.69)
df_result.T.sort_values(by=1, ascending=False).head(50)

        0         1
커플    0.0  0.006931
속     0.0  0.006931
클럽    0.0  0.006931
핫     0.0  0.006931
춤     0.0  0.006931
남미    0.0  0.006931
앵     0.0  0.006931
초급    0.0  0.006931
센     0.0  0.006931
콩     0.0  0.006931
맛집    0.0  0.006931
바     0.0  0.006931
방콕    0.0  0.006931
파타야   0.0  0.006931
완성    0.0  0.006931
교환    0.0  0.006931
크루    0.0  0.006931
에버    0.0  0.006931
라틴    0.0  0.006931
생일    0.0  0.006931
오픈    0.0  0.006931
홍     0.0  0.006931
달     0.0  0.006931
정모    0.0  0.006931
설     0.0  0.006931
스터디   0.0  0.006931
강남    0.0  0.006931
슈얼    0.0  0.006931
수원    0.0  0.006931
살사    0.0  0.006931
여기    0.0  0.006931
아카데미  0.0  0.006931
활동    0.0  0.006931
공연    0.0  0.006931
영어    0.0  0.006931
부대    0.0  0.006931
홍대    0.0  0.006931
텐션    0.0  0.006931
베이직   0.0  0.006931
반     0.0  0.006931
신청    0.0  0.006931
사람    0.0  0.006931
직장    0.0  0.006931
취미    0.0  0.006931
바차타   0.0  0.006931
소셜    0.0  0.006931
미군    0.0  0.006931
주차    0.0  0.006931
사랑    0.0  0.006931
맘보    0.0  0.006931

박조은 튜토리얼 - https://colab.research.google.com/github/corazzon/inflearn-new-year-event-2020/blob/master/02-inflearn-newyear-event-text-analysis.ipynb#scrollTo=Bdn-tuClu17Q

In [32]:
feature_vector = df_result.iloc[0]
feature_vector

정모    0.000000
부대    0.000000
마드    0.006931
커플    0.000000
공연    0.000000
        ...
달     0.000000
생활    0.000000
강남    0.000000
청담    0.006931
대구    0.006931
Name: 0, Length: 183, dtype: float64

In [39]:
# 위에서 구한 단어벡터를 더하면 단어가 전체에서 등장하는 횟수를 알 수 있습니다.
# 벡터화 된 피처를 확인해 봄
# Bag of words 에 몇 개의 단어가 들어있는지 확인
dist = np.sum(feature_vector, axis=0)
dist

0.5753121598647546