Manually doing TF-IDF: https://towardsdatascience.com/natural-language-processing-feature-engineering-using-tf-idf-e8b9d00e7e76

In [61]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

%matplotlib inline
# 시각화 결과가 선명하게 표시되도록
%config InlineBackend.figure_format = 'retina'

In [62]:
df = pd.read_csv("combined_wrangling_db.csv")
df.shape

(100, 248)

In [63]:
df.head()

,PTfreq,PT관련명사,PTfreq.1,PT관련서술어,PTfreq.2,PT관련명사.1,PTfreq.3,PT관련서술어.1,검도freq,검도관련명사,...,핫요가freq.1,핫요가관련서술어,헬스freq,헬스관련명사,헬스freq.1,헬스관련서술어,힙레freq,힙레관련명사,힙레freq.1,힙레관련서술어
0,263,운동,13,많은,263,운동,13,많은,2051,검도,...,238,좋아요,1306,운동,110,좋아요,747,힙,76,열리는
1,164,헬스,13,좋아요,164,헬스,13,좋아요,596,운동,...,202,아쉬,953,헬스,107,챌,710,발레,46,자세한
2,102,다이어트,12,들,102,다이어트,12,들,522,검,...,73,다양한,336,다이어트,54,좋은,478,운동,42,이어
3,83,필라테스,9,해서,83,필라테스,9,해서,451,도관,...,69,소소한,270,팔,53,좋,464,포레스티,40,바꿀
4,64,니스,9,좋은,64,니스,9,좋은,232,동검,...,58,들,263,필라테스,47,하면,452,벌,38,되는

In [64]:
df['PT관련명사']

0       운동
1       헬스
2     다이어트
3     필라테스
4       니스
      ...
95     퍼스널
96     코로나
97      교정
98     휘트니
99       손
Name: PT관련명사, Length: 100, dtype: object

In [73]:
bagOfWordsA = df['살사관련명사'].to_list()
print(bagOfWordsA)
len(bagOfWordsA)

['살사', '바차타', '댄스', '라틴', '동호회', '홍대', '취미', '여행', '수업', '강습', '쿠바', '강남', '운동', '춤', '클럽', '소셜', '다이어트', '영어', '파티', '공연', '텐션', '활동', '파타야', '쌤', '바', '정모', '방콕', '키', '좀바', '맛집', '모임', '시간', '클래스', '일상', '오사카', '오픈', '직장', '수원', '나', '커플', '일본', '것', '사진', '중', '부산', '초급', '반', '번', '생활', '주차', '핫', '설', '예약', '연말', '에버', '스다', '시시시', '슈얼', '홍', '맘보', '오늘', '크루', '연습', '연휴', '아카데미', '차', '신청', '베이직', '금요일', '토요일', '수요일', '음악', '소통', '주', '시작', '하바나', '이태원', '친구', '속', '플레이스', '미군', '부대', '거', '팔', '감사', '일요일', '중급', '사람', '서울', '여기', '이번', '수강', '댄서', '술', '스터디', '언어', '교환', '한곡', '벨', '남미']

100

In [75]:
bagOfWordsB = df['바차타관련명사'].to_list()
print(bagOfWordsB)
len(bagOfWordsB)

['살사', '바차타', '댄스', '라틴', '동호회', '홍대', '취미', '여행', '수업', '강습', '강남', '춤', '소셜', '운동', '클럽', '다이어트', '파티', '에버', '영어', '텐션', '활동', '공연', '파타야', '쌤', '키', '좀바', '방콕', '모임', '커플', '나', '오사카', '바', '부산', '정모', '수원', '클래스', '일상', '쿠바', '직장', '생활', '일본', '사진', '슈얼', '팔', '반', '초급', '스다', '연말', '시간', '맛집', '베이직', '중', '핫', '주차', '크루', '신청', '아카데미', '연습', '소통', '맘보', '것', '홍', '번', '주', '차', '설', '시작', '콜', '미군', '부대', '오픈', '음악', '새해', '여기', '달', '한곡', '완성', '거', '사랑', '블랙', '센', '콩', '속', '이번', '앵', '스터디', '언어', '교환', '특강', '서울', '벨', '영상', '친구', '전설', '수강', '토요일', '사람', '우리', '남미', '생일']

100

In [76]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))
print(uniqueWords)
len(uniqueWords)

{'직장', '신청', '연습', '영어', '센', '방콕', '영상', '일상', '금요일', '콩', '소통', '음악', '여행', '전설', '바차타', '댄스', '키', '스다', '운동', '주', '강남', '부산', '이태원', '교환', '하바나', '시간', '남미', '오사카', '술', '것', '플레이스', '차', '예약', '블랙', '주차', '중', '텐션', '사람', '수강', '벨', '서울', '수업', '쌤', '팔', '설', '콜', '앵', '일본', '연말', '번', '홍', '파타야', '소셜', '댄서', '맘보', '이번', '중급', '쿠바', '슈얼', '토요일', '좀바', '속', '달', '사랑', '라틴', '우리', '거', '여기', '에버', '반', '연휴', '시작', '춤', '핫', '오늘', '스터디', '아카데미', '수원', '크루', '생활', '언어', '일요일', '사진', '맛집', '클럽', '오픈', '홍대', '모임', '초급', '바', '정모', '커플', '한곡', '수요일', '완성', '강습', '활동', '공연', '새해', '살사', '친구', '동호회', '생일', '시시시', '나', '미군', '클래스', '특강', '다이어트', '파티', '취미', '부대', '감사', '베이직'}

114

In [77]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

In [78]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [79]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)

In [54]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [55]:
idfs = computeIDF([numOfWordsA, numOfWordsB])

In [56]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [57]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df_result = pd.DataFrame([tfidfA, tfidfB])

In [58]:
df_result

,직장,신청,연습,영어,센,방콕,영상,일상,금요일,콩,...,나,미군,클래스,특강,다이어트,파티,취미,부대,감사,베이직
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.006931,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.006931,0.0
1,0.0,0.0,0.0,0.0,0.006931,0.0,0.006931,0.0,0.000000,0.006931,...,0.0,0.0,0.0,0.006931,0.0,0.0,0.0,0.0,0.000000,0.0

In [60]:
# 0이 키네시스, 1가 차바타
# 높은 순으로 정렬을 했다는 것은 바차타에는 없고(=0), 키네시스에는 있다는 것(=0.69)
df_result.T.sort_values(by=1, ascending=False).head(60)

             0         1
달     0.000000  0.006931
콩     0.000000  0.006931
완성    0.000000  0.006931
콜     0.000000  0.006931
앵     0.000000  0.006931
새해    0.000000  0.006931
생일    0.000000  0.006931
전설    0.000000  0.006931
특강    0.000000  0.006931
블랙    0.000000  0.006931
사랑    0.000000  0.006931
영상    0.000000  0.006931
우리    0.000000  0.006931
센     0.000000  0.006931
여기    0.000000  0.000000
맛집    0.000000  0.000000
사진    0.000000  0.000000
일요일   0.006931  0.000000
언어    0.000000  0.000000
생활    0.000000  0.000000
크루    0.000000  0.000000
수원    0.000000  0.000000
아카데미  0.000000  0.000000
라틴    0.000000  0.000000
스터디   0.000000  0.000000
에버    0.000000  0.000000
오늘    0.006931  0.000000
핫     0.000000  0.000000
클럽    0.000000  0.000000
시작    0.000000  0.000000
연휴    0.006931  0.000000
거     0.000000  0.000000
반     0.000000  0.000000
춤     0.000000  0.000000
직장    0.000000  0.000000
오픈    0.000000  0.000000
친구    0.000000  0.000000
감사    0.006931  0.000000
부대    0.000000  0.000000
취미    0.000000  0.000000
파티    0.000000  0.000000
다이어트  0.000000  0.000000
클래스   0.000000  0.000000
미군    0.000000  0.000000
나     0.000000  0.000000
시시시   0.006931  0.000000
동호회   0.000000  0.000000
살사    0.000000  0.000000
홍대    0.000000  0.000000
공연    0.000000  0.000000
활동    0.000000  0.000000
강습    0.000000  0.000000
수요일   0.006931  0.000000
한곡    0.000000  0.000000
커플    0.000000  0.000000
정모    0.000000  0.000000
바     0.000000  0.000000
속     0.000000  0.000000
모임    0.000000  0.000000
초급    0.000000  0.000000

박조은 튜토리얼 - https://colab.research.google.com/github/corazzon/inflearn-new-year-event-2020/blob/master/02-inflearn-newyear-event-text-analysis.ipynb#scrollTo=Bdn-tuClu17Q

In [32]:
feature_vector = df_result.iloc[0]
feature_vector

정모    0.000000
부대    0.000000
마드    0.006931
커플    0.000000
공연    0.000000
        ...
달     0.000000
생활    0.000000
강남    0.000000
청담    0.006931
대구    0.006931
Name: 0, Length: 183, dtype: float64

In [39]:
# 위에서 구한 단어벡터를 더하면 단어가 전체에서 등장하는 횟수를 알 수 있습니다.
# 벡터화 된 피처를 확인해 봄
# Bag of words 에 몇 개의 단어가 들어있는지 확인
dist = np.sum(feature_vector, axis=0)
dist

0.5753121598647546